config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
      
  resources :users, only:[:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    validates :title, presence: true
    validates :body, length: {minimum:2, maximum: 200}
    validates :body, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  def create
    @book = current_user.books.new(book_params)
    @user = current_user
    if @book.save
      flash.notice = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      flash.alert = "error"
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash.notice = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def new
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
  <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
        <span class="fas fa-heart"></span><%= book.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        <span class="far fa-heart"></span><%= book.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	<h1>Editing Book</h1>
<% if flash[:notice]%>
  <div>
    <%= flash[:notice]%>
  </div>
<%end%>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <div><%= message %><div>
  <% end %>
<% end %>

<%= form_with model:@book, local:true do |f| %>
  <div class="form-group">
  <h4>Title</h4>
  <%= f.text_field :title, class:"form-control book_title" %>
  </div>
  
  <div class="form-group">
  <h4>Body</h4>
  <%= f.text_area :body, class:"form-control book_body" %>
  </div>
  
  <div class="form-group">
    <%= f.submit 'Update Book', class:"btn btn-success" %>
  </div>
<% end %>

<%= link_to "Show", book_path(@book) %> |
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'users/info', user: @user %>
    <%= render 'users/new', book: @book %>
    </div>
  <div class='col-md-8 offset-md-1'>
  <h2>Books</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      
      <tbody>
          <% @books.each do |book|%>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 5, 5, fallback: "no_image.svg", size: "50x50"%>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></</td>
            <td><%= render 'books/favorite', book: book %></td>
            <td><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'users/info', user: @user %>
    <%= render 'users/new', book: @newbook %>
    </div>
  <div class='col-md-8 offset-md-1'>
  <h2>Book detail</h2>
    <table class='table table-hover table-inverse'>
      <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 5, 5, fallback: "no_image.svg", size: "50x50"%></br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></</td>
            <td><%= render 'books/favorite', book: @book %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book) %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
            <% end %>
          </tr>
      </tbody>
    </table>
    
    <div>
      <p>コメント数:<%= @book.book_comments.count %></p>
      <table>
      <tbody>
        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
                <%= link_to user_path(book_comment.user) do %>
                  <%= attachment_image_tag book_comment.user, :profile_image, :fill, 5, 5, fallback: "no_image.svg", size: "50x50"%>
                <% end %>
            </td>
            <td><%= book_comment.user.name %></td>
            <td><%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
            <td>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
      </table>
      </div>
      <div>
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
      </div>

    </div>
    
  </div>
</div>